(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/Pump' *)
(* @OBJECTFLAGS := '0, 8' *)
(* Режимы работы насоса по ISA-88 *)
TYPE E_PumpMode :
(
    PUMP_MODE_OOS := 0,        (* Out of Service - выведен из работы *)
    PUMP_MODE_LOCAL := 1,      (* Местное управление *)
    PUMP_MODE_MANUAL := 2,     (* Ручное управление от SCADA *)
    PUMP_MODE_AUTO := 3       (* Автоматическое управление *)
);
END_TYPE
